In [102]:
import pandas as pd
import matplotlib.pyplot as plt

In [103]:
ls

FRB_G19.csv               Untitled.ipynb
Impact_Vehicule_COVID-19/ python-api-challenge/

In [104]:
# Import csv via panda
FRB_COVID_data = pd.read_csv("FRB_G19.csv")
FRB_COVID_data.head(960)

,Series Description,"Percent change of total consumer credit, seasonally adjusted at an annual rate","Percent change of total revolving consumer credit, seasonally adjusted at an annual rate","Percent change of total nonrevolving consumer credit, seasonally adjusted at an annual rate","Total consumer credit owned and securitized, seasonally adjusted level","Revolving consumer credit owned and securitized, seasonally adjusted level","Nonrevolving consumer credit owned and securitized, seasonally adjusted level","Total consumer credit owned and securitized, not seasonally adjusted level","Total securitized consumer credit, not seasonally adjusted level","Total consumer credit owned and securitized by depository institutions, not seasonally adjusted level",...,"Finance rate on personal loans at commercial banks, 24 month loan; not seasonally adjusted","Commercial bank interest rate on credit card plans, all accounts; not seasonally adjusted","Commercial bank interest rate on credit card plans, accounts assessed interest; not seasonally adjusted","New car average finance rate at auto finance companies, not seasonally adjusted (discontinued after January 2011)","Weighted-average maturity of new car loans at auto finance companies, not seasonally adjusted (discontinued after January 2011)","Loan-to-value ratio of new car loans at auto finance companies, not seasonally adjusted (discontinued after January 2011)","Average amount financed for new car loans at auto finance companies, not seasonally adjusted (discontinued after January 2011)","Average maturity of new car loans at finance companies, amount of finance weighted, not seasonally adjusted","Average finance rate of new car loans at finance companies, amount of finance weighted, not seasonally adjusted","Average amount financed for new car loans at finance companies, not seasonally adjusted"
0,Unit:,Percent,Percent,Percent,Currency,Currency,Currency,Currency,Currency,Currency,...,Percent,Percent,Percent,Percent,Months,Percent,Currency,Months,Percent,Currency
1,Multiplier:,1,1,1,1000000,1000000,1000000,1000000,1000000,1000000,...,1,1,1,1,1,1,1,1,1,1
2,Currency:,USD,USD,USD,USD,USD,USD,USD,USD,USD,...,USD,USD,USD,USD,USD,USD,USD,USD,USD,USD
3,Unique Identifier:,G19/CCOUT/DTCTL_@%A_BA.M,G19/CCOUT/DTCTLR_@%A_BA.M,G19/CCOUT/DTCTLN_@%A_BA.M,G19/CCOUT/DTCTL.M,G19/CCOUT/DTCTLR.M,G19/CCOUT/DTCTLN.M,G19/CCOUT/DTCTL_N.M,G19/CCOUT/DTCNL_N.M,G19/CCOUT/DTCTLHD_N.M,...,G19/TERMS/RIFLPBCIPLM24_N.M,G19/TERMS/RIFSPBCICC_N.M,G19/TERMS/RIFSPBCICCI_N.M,G19/TERMS/H0.RIFLPCFAN_N.M,G19/TERMS/H0.DTCTLVNM_N.M,G19/TERMS/H0.DTCTLVNL_N.M,G19/TERMS/H0.DTCTLVNA_N.M,G19/TERMS/DTCTLVENM_N.M,G19/TERMS/RIELPCFAN_N.M,G19/TERMS/DTCTLVENA_N.M
4,Time Period,DTCTL_@%A_BA.M,DTCTLR_@%A_BA.M,DTCTLN_@%A_BA.M,DTCTL.M,DTCTLR.M,DTCTLN.M,DTCTL_N.M,DTCNL_N.M,DTCTLHD_N.M,...,RIFLPBCIPLM24_N.M,RIFSPBCICC_N.M,RIFSPBCICCI_N.M,H0.RIFLPCFAN_N.M,H0.DTCTLVNM_N.M,H0.DTCTLVNL_N.M,H0.DTCTLVNA_N.M,DTCTLVENM_N.M,RIELPCFAN_N.M,DTCTLVENA_N.M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2022-03,10.11,25.75,5.35,4637069.03,1096869.11,3540199.92,4577611.19,1256.39,1830909.36,...,ND,ND,ND,NaN,NaN,NaN,NaN,66.29,4.41,37991.37
956,2022-04,7.38,15.09,4.99,4665575.21,1110666.40,3554908.81,4608598.69,1316.26,1856081.89,...,ND,ND,ND,NaN,NaN,NaN,NaN,ND,ND,ND
957,2022-05,6.92,10.39,5.84,4692486.22,1120278.49,3572207.73,4650274.56,1381.54,1880933.05,...,8.73,15.13,16.65,NaN,NaN,NaN,NaN,ND,ND,ND
958,2022-06,8.59,15.46,6.43,4726073.38,1134712.89,3591360.49,4695209.26,1447.08,1915051.04,...,ND,ND,ND,NaN,NaN,NaN,NaN,66.45,4.98,38044.46
959,2022-07,6.79,13.00,4.82,4752798.59,1147003.37,3605795.22,4715480.02,1596.01,1925396.34,...,ND,ND,ND,NaN,NaN,NaN,NaN,ND,ND,ND

In [105]:
type(FRB_COVID_data)

pandas.core.frame.DataFrame

In [106]:
#create dataframe displaying avg New Car Auto Loan rates for COVID date range 
df2=FRB_COVID_data[["Series Description","Average finance rate of new car loans at finance companies, amount of finance weighted, not seasonally adjusted"]].iloc[931:967]
df2

,Series Description,"Average finance rate of new car loans at finance companies, amount of finance weighted, not seasonally adjusted"
931,2020-03,6.13
932,2020-04,ND
933,2020-05,ND
934,2020-06,4.80
935,2020-07,ND
936,2020-08,ND
937,2020-09,4.98
938,2020-10,ND
939,2020-11,ND
940,2020-12,5.07
941,2021-01,ND
942,2021-02,ND
943,2021-03,4.79
944,2021-04,ND
945,2021-05,ND
946,2021-06,4.86
947,2021-07,ND
948,2021-08,ND
949,2021-09,4.54
950,2021-10,ND
951,2021-11,ND
952,2021-12,4.37
953,2022-01,ND
954,2022-02,ND
955,2022-03,4.41
956,2022-04,ND
957,2022-05,ND
958,2022-06,4.98
959,2022-07,ND
960,2022-08,ND
961,2022-09,5.47
962,2022-10,ND
963,2022-11,ND
964,2022-12,6.07
965,2023-01,ND
966,2023-02,ND

In [107]:
# remove months that report ND (no data) to show COVID quarters
clean_df = df2.drop(labels = [932,933,935,936,938,939,941,942,944,945,947,948,950,951,953,954,956,957,959,960,962,963,965,966], axis = 0, inplace = False)
clean_df

,Series Description,"Average finance rate of new car loans at finance companies, amount of finance weighted, not seasonally adjusted"
931,2020-03,6.13
934,2020-06,4.80
937,2020-09,4.98
940,2020-12,5.07
943,2021-03,4.79
946,2021-06,4.86
949,2021-09,4.54
952,2021-12,4.37
955,2022-03,4.41
958,2022-06,4.98
961,2022-09,5.47
964,2022-12,6.07

In [108]:
#rename columns 
df3= clean_df.rename(columns={"Series Description":"COVID Quarters","Average finance rate of new car loans at finance companies, amount of finance weighted, not seasonally adjusted":"Average New Car Auto Loan Rates"})
df3

    COVID Quarters Average New Car Auto Loan Rates
931        2020-03                            6.13
934        2020-06                            4.80
937        2020-09                            4.98
940        2020-12                            5.07
943        2021-03                            4.79
946        2021-06                            4.86
949        2021-09                            4.54
952        2021-12                            4.37
955        2022-03                            4.41
958        2022-06                            4.98
961        2022-09                            5.47
964        2022-12                            6.07

In [109]:
df3.dtypes

COVID Quarters                     object
Average New Car Auto Loan Rates    object
dtype: object

In [116]:
df3['COVID Quarters']=pd.to_numeric(df3['COVID Quarters'],errors='coerce')

In [112]:
df3['COVID Quarters']=df3['COVID Quarters'].astype(float)

ValueError: could not convert string to float: '2020-03'

In [118]:
avg_rates_line = df3.plot.line(x='COVID Quarters', y='Average New Car Auto Loan Rates', lw = 2, title = 'New Car Auto Loan Rates during COVID', fontsize = 8)
avg_rates_line

TypeError: no numeric data to plot